# Generated by Django 5.0.4 on 2024-05-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='tolandi',
            field=models.BooleanField(default=False),
        ),
    ]
