# Generated by Django 5.0.4 on 2024-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0003_alter_buyurtma_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='raqam',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
