# Generated by Django 5.0.4 on 2024-05-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ichimlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('narx', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ichimlik',
                'verbose_name_plural': 'Ichimliklar',
            },
        ),
        migrations.CreateModel(
            name='Joy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Joy',
                'verbose_name_plural': 'Joylar',
            },
        ),
        migrations.CreateModel(
            name='Taom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('narx', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
            },
        ),
    ]
