# Generated by Django 5.0.4 on 2024-05-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joy',
            name='orin',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
