# Generated by Django 5.0.4 on 2024-05-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_joy_orin'),
    ]

    operations = [
        migrations.AddField(
            model_name='joy',
            name='band',
            field=models.BooleanField(default=False),
        ),
    ]
